development:
  key: j2P6VGukLNw61k0OEd2i7A
  secret: yaNRnZDKHf2nOMPVqviaeleNdfRNQul4l95ePFCcvBE
  access_token: 12897152-8Q5QRR1pXGSHAvacoCEgwAl4HTRNT0zoUJ1plGqgL
  access_token_secret: DDc2eNHRfcXEHHbTYNNBGcMahTsvu5pBoI96fctQFZrmk